// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wxopdgorwlaruagbbolx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind4b3BkZ29yd2xhcnVhZ2Jib2x4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NTYyODQsImV4cCI6MjA3MzMzMjI4NH0.UcQls3rdLtsmrq6fFrvkzZt71pBSqR2SE6HFvbl9K7U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});